[package]
name = "markov"
version = "0.1.0"
authors = ["Trondby <Trondby@users.noreply.github.com>"]
edition = "2024"

[dependencies]
rand = "0.9.0"

[profile.release]
debug = false
panic = "abort"
strip = true
lto = true
