[package]
name = "markov"
version = "0.1.0"
authors = ["Trondby <Trondby@users.noreply.github.com>"]
edition = "2018"

[dependencies]
rand = "0.8.5"

[profile.release]
debug = false
panic = 'abort'
strip = true